/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Mon Jan  6 00:29:29 2025.
 */

#include <string.h>

#include "simple.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int simple_driver_heartbeat_pack(
    uint8_t *dst_p,
    const struct simple_driver_heartbeat_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->driver_heartbeat_cmd, 0u, 0xffu);

    return (1);
}

int simple_driver_heartbeat_unpack(
    struct simple_driver_heartbeat_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->driver_heartbeat_cmd = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t simple_driver_heartbeat_driver_heartbeat_cmd_encode(double value)
{
    return (uint8_t)(value);
}

double simple_driver_heartbeat_driver_heartbeat_cmd_decode(uint8_t value)
{
    return ((double)value);
}

bool simple_driver_heartbeat_driver_heartbeat_cmd_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int simple_io_debug_pack(
    uint8_t *dst_p,
    const struct simple_io_debug_t *src_p,
    size_t size)
{
    uint8_t io_debug_test_signed;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u8(src_p->io_debug_test_unsigned, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->io_debug_test_enum, 0u, 0xffu);
    io_debug_test_signed = (uint8_t)src_p->io_debug_test_signed;
    dst_p[2] |= pack_left_shift_u8(io_debug_test_signed, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->io_debug_test_float, 0u, 0xffu);

    return (4);
}

int simple_io_debug_unpack(
    struct simple_io_debug_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t io_debug_test_signed;

    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->io_debug_test_unsigned = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->io_debug_test_enum = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    io_debug_test_signed = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->io_debug_test_signed = (int8_t)io_debug_test_signed;
    dst_p->io_debug_test_float = unpack_right_shift_u8(src_p[3], 0u, 0xffu);

    return (0);
}

uint8_t simple_io_debug_io_debug_test_unsigned_encode(double value)
{
    return (uint8_t)(value);
}

double simple_io_debug_io_debug_test_unsigned_decode(uint8_t value)
{
    return ((double)value);
}

bool simple_io_debug_io_debug_test_unsigned_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t simple_io_debug_io_debug_test_enum_encode(double value)
{
    return (uint8_t)(value);
}

double simple_io_debug_io_debug_test_enum_decode(uint8_t value)
{
    return ((double)value);
}

bool simple_io_debug_io_debug_test_enum_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int8_t simple_io_debug_io_debug_test_signed_encode(double value)
{
    return (int8_t)(value);
}

double simple_io_debug_io_debug_test_signed_decode(int8_t value)
{
    return ((double)value);
}

bool simple_io_debug_io_debug_test_signed_is_in_range(int8_t value)
{
    (void)value;

    return (true);
}

uint8_t simple_io_debug_io_debug_test_float_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double simple_io_debug_io_debug_test_float_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool simple_io_debug_io_debug_test_float_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int simple_motor_cmd_pack(
    uint8_t *dst_p,
    const struct simple_motor_cmd_t *src_p,
    size_t size)
{
    uint8_t motor_cmd_steer;

    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    motor_cmd_steer = (uint8_t)src_p->motor_cmd_steer;
    dst_p[0] |= pack_left_shift_u8(motor_cmd_steer, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->motor_cmd_drive, 4u, 0xf0u);

    return (1);
}

int simple_motor_cmd_unpack(
    struct simple_motor_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t motor_cmd_steer;

    if (size < 1u) {
        return (-EINVAL);
    }

    motor_cmd_steer = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);

    if ((motor_cmd_steer & (1u << 3)) != 0u) {
        motor_cmd_steer |= 0xf0u;
    }

    dst_p->motor_cmd_steer = (int8_t)motor_cmd_steer;
    dst_p->motor_cmd_drive = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);

    return (0);
}

int8_t simple_motor_cmd_motor_cmd_steer_encode(double value)
{
    return (int8_t)(value - -5.0);
}

double simple_motor_cmd_motor_cmd_steer_decode(int8_t value)
{
    return ((double)value + -5.0);
}

bool simple_motor_cmd_motor_cmd_steer_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 10));
}

uint8_t simple_motor_cmd_motor_cmd_drive_encode(double value)
{
    return (uint8_t)(value);
}

double simple_motor_cmd_motor_cmd_drive_decode(uint8_t value)
{
    return ((double)value);
}

bool simple_motor_cmd_motor_cmd_drive_is_in_range(uint8_t value)
{
    return (value <= 9u);
}

int simple_motor_status_pack(
    uint8_t *dst_p,
    const struct simple_motor_status_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->motor_status_wheel_error, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u16(src_p->motor_status_speed_kph, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->motor_status_speed_kph, 8u, 0xffu);

    return (3);
}

int simple_motor_status_unpack(
    struct simple_motor_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->motor_status_wheel_error = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->motor_status_speed_kph = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->motor_status_speed_kph |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);

    return (0);
}

uint8_t simple_motor_status_motor_status_wheel_error_encode(double value)
{
    return (uint8_t)(value);
}

double simple_motor_status_motor_status_wheel_error_decode(uint8_t value)
{
    return ((double)value);
}

bool simple_motor_status_motor_status_wheel_error_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t simple_motor_status_motor_status_speed_kph_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double simple_motor_status_motor_status_speed_kph_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool simple_motor_status_motor_status_speed_kph_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
