
 
/**
 * This file was generated by GHESBORO OMAR!! impazzisco - version 0.1.
 */

#ifndef EXPECTED_H
#define EXPECTED_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define EXPECTED_MSG_0_FRAME_ID (0x1u)
#define EXPECTED_MSG_1_FRAME_ID (0x2u)
#define EXPECTED_MSG_2_FRAME_ID (0x3u)
#define EXPECTED_MSG_3_FRAME_ID (0x4u)

/* Frame lengths in bytes. */
#define EXPECTED_MSG_0_LENGTH (8u)
#define EXPECTED_MSG_1_LENGTH (8u)
#define EXPECTED_MSG_2_LENGTH (8u)
#define EXPECTED_MSG_3_LENGTH (1u)

/* Extended or standard frame types. */
#define EXPECTED_MSG_0_IS_EXTENDED (0)
#define EXPECTED_MSG_1_IS_EXTENDED (0)
#define EXPECTED_MSG_2_IS_EXTENDED (0)
#define EXPECTED_MSG_3_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */
#define EXPECTED_MSG_0_CYCLE_TIME_MS (0u)
#define EXPECTED_MSG_1_CYCLE_TIME_MS (0u)
#define EXPECTED_MSG_2_CYCLE_TIME_MS (10u)
#define EXPECTED_MSG_3_CYCLE_TIME_MS (0u)

/* Signal choices. */
#define EXPECTED_MSG_2_ENUM_SIG_0_VALUE_0_CHOICE (0u)
#define EXPECTED_MSG_2_ENUM_SIG_0_VALUE_1_CHOICE (1u)
#define EXPECTED_MSG_2_ENUM_SIG_0_VALUE_15_CHOICE (15u)

/* Frame Names. */
#define EXPECTED_MSG_0_NAME ("msg_0")
#define EXPECTED_MSG_1_NAME ("msg_1")
#define EXPECTED_MSG_2_NAME ("msg_2")
#define EXPECTED_MSG_3_NAME ("msg_3")

/* Signal Names. */
#define EXPECTED_MSG_0_STD_SIG_0_NAME ("std_sig_0")
#define EXPECTED_MSG_0_MUX_SIG_0_NAME ("mux_sig_0")
#define EXPECTED_MSG_1_MUX_SIG_1_NAME ("mux_sig_1")
#define EXPECTED_MSG_2_ENUM_SIG_0_NAME ("enum_sig_0")
#define EXPECTED_MSG_3_STD_SIG_1_NAME ("std_sig_1")
#define EXPECTED_MSG_3_STD_SIG_2_NAME ("std_sig_2")

/* Struct */
/* Declarations */ 


/* Signals in message msg_0 */
struct expected_msg_0_t {

    /**
     * Range: 
     * Scale:
     * Offset:
     * start value: 0
     * send type: unset
     * get start bit: 0
     * get size: 4
     */
    uint8_t std_sig_0;
    
    /**
     * Range: 
     * Scale:
     * Offset:
     * start value: 0
     * send type: unset
     * get start bit: 4
     * get size: 18
     */
    uint8_t mux_sig_0;
    
};

/* Signals in message msg_1 */
struct expected_msg_1_t {

    /**
     * Range: 
     * Scale:
     * Offset:
     * start value: 0
     * send type: unset
     * get start bit: 0
     * get size: 18
     */
    uint8_t mux_sig_1;
    
};

/* Signals in message msg_2 */
struct expected_msg_2_t {

    /**
     * Range: 
     * Scale:
     * Offset:
     * start value: 0
     * send type: on-change_with_repetition
     * get start bit: 0
     * get size: 4
     */
    uint8_t enum_sig_0;
    
};

/* Signals in message msg_3 */
struct expected_msg_3_t {

    /**
     * Range: 
     * Scale:
     * Offset:
     * start value: 0
     * send type: unset
     * get start bit: 0
     * get size: 4
     */
    uint8_t std_sig_1;
    
    /**
     * Range: 
     * Scale:
     * Offset:
     * start value: 0
     * send type: unset
     * get start bit: 4
     * get size: 4
     */
    uint8_t std_sig_2;
    
};



#define BUS_NAME "bus_0"

// typedef struct for a message
typedef struct {
    int id;
} Message;

#ifdef __cplusplus
}
#endif

#endif
